/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrustIndexRouteImport } from './routes/trust.index'
import { Route as TrustResultsRouteImport } from './routes/trust.results'
import { Route as TrustPricingRouteImport } from './routes/trust.pricing'
import { Route as TrustGuaranteesRouteImport } from './routes/trust.guarantees'
import { Route as TrustEthicalMarketingRouteImport } from './routes/trust.ethical-marketing'
import { Route as TrustAuthorRightsRouteImport } from './routes/trust.author-rights'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustIndexRoute = TrustIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrustRoute,
} as any)
const TrustResultsRoute = TrustResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TrustRoute,
} as any)
const TrustPricingRoute = TrustPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => TrustRoute,
} as any)
const TrustGuaranteesRoute = TrustGuaranteesRouteImport.update({
  id: '/guarantees',
  path: '/guarantees',
  getParentRoute: () => TrustRoute,
} as any)
const TrustEthicalMarketingRoute = TrustEthicalMarketingRouteImport.update({
  id: '/ethical-marketing',
  path: '/ethical-marketing',
  getParentRoute: () => TrustRoute,
} as any)
const TrustAuthorRightsRoute = TrustAuthorRightsRouteImport.update({
  id: '/author-rights',
  path: '/author-rights',
  getParentRoute: () => TrustRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/process': typeof ProcessRoute
  '/results': typeof ResultsRoute
  '/solutions': typeof SolutionsRoute
  '/trust': typeof TrustRouteWithChildren
  '/trust/author-rights': typeof TrustAuthorRightsRoute
  '/trust/ethical-marketing': typeof TrustEthicalMarketingRoute
  '/trust/guarantees': typeof TrustGuaranteesRoute
  '/trust/pricing': typeof TrustPricingRoute
  '/trust/results': typeof TrustResultsRoute
  '/trust/': typeof TrustIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/process': typeof ProcessRoute
  '/results': typeof ResultsRoute
  '/solutions': typeof SolutionsRoute
  '/trust/author-rights': typeof TrustAuthorRightsRoute
  '/trust/ethical-marketing': typeof TrustEthicalMarketingRoute
  '/trust/guarantees': typeof TrustGuaranteesRoute
  '/trust/pricing': typeof TrustPricingRoute
  '/trust/results': typeof TrustResultsRoute
  '/trust': typeof TrustIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/process': typeof ProcessRoute
  '/results': typeof ResultsRoute
  '/solutions': typeof SolutionsRoute
  '/trust': typeof TrustRouteWithChildren
  '/trust/author-rights': typeof TrustAuthorRightsRoute
  '/trust/ethical-marketing': typeof TrustEthicalMarketingRoute
  '/trust/guarantees': typeof TrustGuaranteesRoute
  '/trust/pricing': typeof TrustPricingRoute
  '/trust/results': typeof TrustResultsRoute
  '/trust/': typeof TrustIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessment'
    | '/contact'
    | '/goals'
    | '/insights'
    | '/process'
    | '/results'
    | '/solutions'
    | '/trust'
    | '/trust/author-rights'
    | '/trust/ethical-marketing'
    | '/trust/guarantees'
    | '/trust/pricing'
    | '/trust/results'
    | '/trust/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/contact'
    | '/goals'
    | '/insights'
    | '/process'
    | '/results'
    | '/solutions'
    | '/trust/author-rights'
    | '/trust/ethical-marketing'
    | '/trust/guarantees'
    | '/trust/pricing'
    | '/trust/results'
    | '/trust'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessment'
    | '/contact'
    | '/goals'
    | '/insights'
    | '/process'
    | '/results'
    | '/solutions'
    | '/trust'
    | '/trust/author-rights'
    | '/trust/ethical-marketing'
    | '/trust/guarantees'
    | '/trust/pricing'
    | '/trust/results'
    | '/trust/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  ContactRoute: typeof ContactRoute
  GoalsRoute: typeof GoalsRoute
  InsightsRoute: typeof InsightsRoute
  ProcessRoute: typeof ProcessRoute
  ResultsRoute: typeof ResultsRoute
  SolutionsRoute: typeof SolutionsRoute
  TrustRoute: typeof TrustRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust/': {
      id: '/trust/'
      path: '/'
      fullPath: '/trust/'
      preLoaderRoute: typeof TrustIndexRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/results': {
      id: '/trust/results'
      path: '/results'
      fullPath: '/trust/results'
      preLoaderRoute: typeof TrustResultsRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/pricing': {
      id: '/trust/pricing'
      path: '/pricing'
      fullPath: '/trust/pricing'
      preLoaderRoute: typeof TrustPricingRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/guarantees': {
      id: '/trust/guarantees'
      path: '/guarantees'
      fullPath: '/trust/guarantees'
      preLoaderRoute: typeof TrustGuaranteesRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/ethical-marketing': {
      id: '/trust/ethical-marketing'
      path: '/ethical-marketing'
      fullPath: '/trust/ethical-marketing'
      preLoaderRoute: typeof TrustEthicalMarketingRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/author-rights': {
      id: '/trust/author-rights'
      path: '/author-rights'
      fullPath: '/trust/author-rights'
      preLoaderRoute: typeof TrustAuthorRightsRouteImport
      parentRoute: typeof TrustRoute
    }
  }
}

interface TrustRouteChildren {
  TrustAuthorRightsRoute: typeof TrustAuthorRightsRoute
  TrustEthicalMarketingRoute: typeof TrustEthicalMarketingRoute
  TrustGuaranteesRoute: typeof TrustGuaranteesRoute
  TrustPricingRoute: typeof TrustPricingRoute
  TrustResultsRoute: typeof TrustResultsRoute
  TrustIndexRoute: typeof TrustIndexRoute
}

const TrustRouteChildren: TrustRouteChildren = {
  TrustAuthorRightsRoute: TrustAuthorRightsRoute,
  TrustEthicalMarketingRoute: TrustEthicalMarketingRoute,
  TrustGuaranteesRoute: TrustGuaranteesRoute,
  TrustPricingRoute: TrustPricingRoute,
  TrustResultsRoute: TrustResultsRoute,
  TrustIndexRoute: TrustIndexRoute,
}

const TrustRouteWithChildren = TrustRoute._addFileChildren(TrustRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  ContactRoute: ContactRoute,
  GoalsRoute: GoalsRoute,
  InsightsRoute: InsightsRoute,
  ProcessRoute: ProcessRoute,
  ResultsRoute: ResultsRoute,
  SolutionsRoute: SolutionsRoute,
  TrustRoute: TrustRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
